cleandb:
	rm -r -d cve_information/cvedatabase/*

createdb:
	python3 newCreateDB.py

querydb:
	python3 newQueryDB.py

queryllm:
	python3 newQueryLLM.py

run:
	python3 newCreateDB.py
	python3 newQueryDB.py
	python3 newQueryLLM.py
